# BookCAT - Contents
---
table:
  Name: Contents
personColumns:
  Person: 'Name,SortBy'
tables:
  Author: 'Person,AuthorContentsLink.PersonID'
  AuthorContentsLink: AuthorContentsLink;Hide
  Book: 'Book,,BookID;ShowAll'
  Chapter: 'Chapter,ContentsID;ShowAll'
  Country: Country
  Keyword: 'Keyword,KeywordContentsLink.KeywordID'
  KeywordContentsLink: KeywordContentsLink;Hide
  Language: Language
  OriginalCountry: 'Country,OriginalCountryID'
  OriginalLanguage: 'Language,OriginalLanguageID'
  OriginalPublisher: 'Publisher,OriginalPublisherID'
  OriginalSeries: 'Series,OriginalSeriesID'
  Publisher: Publisher;ShowAll
  Series: Series
  Type: 'ContentsType,TypeID'
tables6:
  Custom04: 'ContentsCustom04,Custom04ID'
  Custom05: 'ContentsCustom05,Custom05ID'
  Custom06: 'ContentsCustom06,Custom06ID'
tables7:
  ContentsCustom: ContentsCustom;ShowAll
  Custom04: 'ContentsCustom04,ContentsCustom.Custom04ID'
  Custom05: 'ContentsCustom05,ContentsCustom.Custom05ID'
  Custom06: 'ContentsCustom06,ContentsCustom.Custom06ID'
tables8:
  CreditContentsLink: 'CreditContentsLink,ContentsID;Hide'
  Credits: 'Person,CreditContentsLink.PersonID'
mainLineTables:
  tables: ContentsCustom
hideColumns:
  columns: 'Custom04ID,Custom05ID,Custom06ID,MarkedQS'
userfields:
  Custom04: Custom04.ContentsCustom04
  Custom05: Custom05.ContentsCustom05
  Custom06: Custom06.ContentsCustom06
  Keyword: 'Keyword.Keyword,Memo'
  OriginalCopyright: 'OriginalCopyright,date'
  OriginalCountry: OriginalCountry.Country
  OriginalLanguage: OriginalLanguage.Language
  OriginalPublisher: OriginalPublisher.Publisher
  OriginalSeries: OriginalSeries.Series
  TitleSort: ContentsSort
  CopyrightDate: 'Book.CopyrightDate,date'
  DateAcquired: 'Book.DateAcquired,Date'
  DateBorrowed: 'Book.DateBorrowed,Date'
  DateDue: 'Book.DateDue,Date'
  EmailOverdueDate: 'Book.EmailOverdueDate,Date'
  EmailReminderDate: 'Book.EmailReminderDate,Date'
  EmailReservedDate: 'Book.EmailReservedDate,Date'
  LastRead: 'Book.LastRead,Date'
  PublishDate: 'Book.PublishDate,date'
  Registered: 'Book.Registered,Date'
  ReservedDate: 'Book.ReservedDate,date'
  Type: Type.ContentsType
userfields8:
  LastModified: 'LastModified,Date'
userfields9:
  LastModified: 'LastModified,S'
userfields10:
  Custom16: 'ContentsCustom.Custom16,Date'
