# CATraxx - Album
---
table:
  Name: Album
  Contents: Tracks
personColumns:
  Artist: 'Name,SortBy'
  ArtistPerson: 'Name,SortBy'
tables:
  AcquiredFrom: AcquiredFrom
  AlbumImage: 'AlbumImage,AlbumID'
  Appraiser: Appraiser
  ArtistAlbumLink: ArtistAlbumLink
  Borrower: Borrower
  Company: Company
  ConditionRecord: ConditionRecord
  ContentsLink: 'ArtistTrackLink,Tracks.TrackID,TrackID'
  ConditionSleeve: ConditionSleeve
  Country: Country
  Distributor: Distributor
  Format: Format
  FormatGroup: 'FormatGroup,Format.FormatGroupID'
  Genre: Genre
  Insurance: Insurance
  Label: Label
  Location: Location
  Owner: Owner
  Packaging: Packaging
  PersonalRating: PersonalRating
  ReservedTo: 'Borrower,ReservedToBorrowerID'
  SPARS: SPARS
  Status: Status
  TapeType: TapeType
  Tracks: 'Track,,AlbumID'
  VinylColor: VinylColor
tables5:
  Artist: 'Artist,ArtistAlbumLink.ArtistID'
  ContentsPerson: 'Artist,ContentsLink.ArtistID'
  Custom05: 'AlbumUserDef05,UserDef05ID'
  Custom06: 'AlbumUserDef06,UserDef06ID'
  Custom07: 'AlbumUserDef07,UserDef07ID'
  Custom08: 'AlbumUserDef08,UserDef08ID'
  Media: 'ItemInfo,,AlbumID'
tables6:
  AlbumCustom: AlbumCustom
  Custom05: 'AlbumCustom05,AlbumCustom.Custom05ID'
  Custom06: 'AlbumCustom06,AlbumCustom.Custom06ID'
  Custom07: 'AlbumCustom07,AlbumCustom.Custom07ID'
  Custom08: 'AlbumCustom08,AlbumCustom.Custom08ID'
  Custom20: 'AlbumCustom20,AlbumCustom.Custom20ID'
  Custom21: 'AlbumCustom21,AlbumCustom.Custom21ID'
  Keyword: 'Keyword,KeywordAlbumLink.KeywordID'
  KeywordAlbumLink: KeywordAlbumLink
tables7:
  Media: 'Media,,AlbumID'
tables8:
  ArrangerTrackLink: 'ArrangerTrackLink,Tracks.TrackID,TrackID'
  Artist: 'ArtistPerson,ArtistAlbumLink.ArtistPersonID'
  ArtistPerformer: 'ArtistPerson,MusicianTrackLink.ArtistPersonID,ArtistPersonID'
  ArtistArranger: 'ArtistPerson,ArrangerTrackLink.ArtistPersonID,ArtistPersonID'
  ArtistAuthor: 'ArtistPerson,AuthorTrackLink.ArtistPersonID,ArtistPersonID'
  AuthorTrackLink: 'AuthorTrackLink,Tracks.TrackID,TrackID'
  ContentsPerson: 'ArtistPerson,ContentsLink.ArtistPersonID'
  Instrument: 'Instrument,MusicianTrackLink.InstrumentID'
  MusicianTrackLink: 'MusicianTrackLink,Tracks.TrackID,TrackID'
  WebLinks: WebLinks
  WebLinkType: 'WebLinkType,WebLinks.TypeID'
tables9:
  AlbumChartInfo: 'AlbumChartInfo,,AlbumID'
  GenreAlbumLink: GenreAlbumLink
  Genre: 'Genre,GenreAlbumLink.GenreID'
  MusicChart: 'MusicChart,AlbumChartInfo.MusicChartID'
  PrimaryGenre: 'Genre,PrimaryGenreID'
mainLineTables:
  tables: 'AlbumCustom,AlbumImage'
hideColumns:
  columns: 'MarkedQS,UserDef05ID,UserDef06ID,UserDef07ID,UserDef08ID'
userfields:
  Cover[1]: 'AlbumImage.Image,Image;Index=1'
  Cover[2]: 'AlbumImage.Image,Image;Index=2'
  Cover[3]: 'AlbumImage.Image,Image;Index=3'
  Cover[4]: 'AlbumImage.Image,Image;Index=4'
  Cover[5]: 'AlbumImage.Image,Image;Index=5'
  Cover[6]: 'AlbumImage.Image,Image;Index=6'
  Cover[7]: 'AlbumImage.Image,Image;Index=7'
  Cover[8]: 'AlbumImage.Image,Image;Index=8'
  Cover[9]: 'AlbumImage.Image,Image;Index=9'
  DateAcquired: 'DateAcquired,date'
  DateBorrowed: 'DateBorrowed,Date'
  DateDue: 'DateDue,Date'
  EmailOverdueDate: 'EmailOverdueDate,Date'
  EmailReminderDate: 'EmailReminderDate,Date'
  EmailReservedDate: 'EmailReservedDate,Date'
  LastPlayed: 'LastPlayed,Date'
  Performers: 'Dummy,Memo'
  PlayingTime: 'PlayingTime,time'
  Registered: 'Registered,Date'
  Released: 'Released,date'
  ReleaseYear: Dummy
  ReservedDate: 'ReservedDate,Date'
  Thumbnail[1]: 'AlbumImage.ImageThumbnail,X;Index=1'
  Thumbnail[2]: 'AlbumImage.ImageThumbnail,X;Index=2'
  Thumbnail[3]: 'AlbumImage.ImageThumbnail,X;Index=3'
  Thumbnail[4]: 'AlbumImage.ImageThumbnail,X;Index=4'
  Thumbnail[5]: 'AlbumImage.ImageThumbnail,X;Index=5'
  Thumbnail[6]: 'AlbumImage.ImageThumbnail,X;Index=6'
  Thumbnail[7]: 'AlbumImage.ImageThumbnail,X;Index=7'
  Thumbnail[8]: 'AlbumImage.ImageThumbnail,X;Index=8'
  Thumbnail[9]: 'AlbumImage.ImageThumbnail,X;Index=9'
  TitleSort: AlbumSort
  Category: Dummy
  Composers: 'Dummy,Memo'
  Conductors: 'Dummy,Memo'
  Orchestras: 'Dummy,Memo'
  Writers: 'Dummy,Memo'
userfields5:
  Custom01: UserDef01
  Custom02: UserDef02
  Custom03: UserDef03
  Custom04: UserDef04
  Custom09: UserDef09
  Custom10: UserDef10
  Custom11: UserDef11
  Custom12: UserDef12
  Custom13: UserDef13
  Custom14: UserDef14
  Custom15: UserDef15
  Custom16: UserDef16
  Custom17: UserDef17
userfields6:
  Custom05: Custom05.AlbumCustom05
  Custom06: Custom06.AlbumCustom06
  Custom07: Custom07.AlbumCustom07
  Custom08: Custom08.AlbumCustom08
  Custom20: Custom20.AlbumCustom20
  Custom21: Custom21.AlbumCustom21
  Custom22: 'Custom22,date'
  Custom23: 'Custom23,date'
  Keyword: 'Keyword.Keyword,Memo'
userfields7:
  LastModified: 'LastModified,Date'
  ReissueDate: 'ReissueDate,date'
userfields8:
  IsArtist: ArtistPerson.Artist
  Artist: ArtistPerson.Name
  LastModified: 'LastModified,S'
  LastPlayed: 'LastPlayed,S'
userfields9:
  Tracks.Item: Tracks.DiscNo
  Media.Item: Media.DiscNo
