# CATraxx - PlayList
---
table:
  Name: Playlist
  Contents: Tracks
personColumns:
  Artist: 'Name,SortBy'
  ArtistPerson: 'Name,SortBy'
tables:
  ContentsLink: 'ArtistTrackLink,Tracks.TrackID,TrackID;Hide'
tables5:
  ContentsPerson: 'Artist,ContentsLink.ArtistID;Hide'
  Tracks: 'Track,PlaylistItems.TrackID;Hide'
tables8:
  Category: 'PlaylistCategory,CategoryID'
  ContentsPerson: 'ArtistPerson,ContentsLink.ArtistPersonID;Hide'
  PlaylistCreatedBy: 'PlaylistCreatedBy,CreatedByID,PlaylistCreatedByID;Hide'
  PlaylistTrack: 'PlaylistTrack,PlaylistID;Hide'
  Status: 'PlaylistStatus,StatusID;Hide'
  Tracks: 'Track,PlaylistTrack.TrackID;Hide'
tables9:
  GenrePlaylisLink: GenrePlaylistLink;Hide
  Genre: 'Genre,GenrePlaylistLink.GenreID;Hide'
  PrimaryGenre: 'Genre,PrimaryGenreID'
hideColumns:
  columns: MarkedQS
userfields8:
  Category: PlayListCategory.Category
  CreationDate: 'CreationDate,Date'
  PlaylistCreatedBy: PlaylistCreatedBy.PlaylistCreatedBy
  FullCategory: PlayListCategory.FullCategory
  PlayingTime: 'PlayingTime,time'
  Status: PlayListStatus.Status
  Type: Title
userfields9:
  PrimaryGenre: PrimaryGenre.Genre
