# CATraxx - WantList
---
table:
  Name: WantList
personColumns:
  ArtistPerson: 'Name,SortBy'
tables:
  Artist: 'ArtistPerson,ArtistWantListLink.ArtistPersonID'
  ArtistWantListLink: 'ArtistWantListLink,WantListID;Hide'
  Format: Format
  FormatGroup: 'FormatGroup,Format.FormatGroupID'
  Label: Label;ShowAll
  OrderedFrom: 'AcquiredFrom,OrderedFromID,AcquiredFromID;ShowAll'
hideColumns:
  columns: 'AcquiredFromID,MarkedQS'
userfields:
  OrderDate: 'OrderDate,date'
  OrderedFrom: OrderedFrom.AcquiredFrom
  Released: 'Released,date'
  Sort: OrderedFrom.AcquiredFromSort
  TitleSort: WantListSort
