# CATraxx - Artist
---
table:
  Name: ArtistPerson
tables5:
  ArtistImage: ArtistImage
  ArtistRelation: ArtistRelation;NoDup
  ArtistType: 'ArtistType,ArtistTypeID;ShowAll'
  Country: Country
  FileLinks: ArtistFileLinks;ShowAll
  RelatedTo: 'Artist,ArtistRelation.RelatedTo'
  WebLinks: ArtistWebLinks;ShowAll
tables8:
  ArtistImage: ArtistPersonImage
  ArtistRelation: 'ArtistPersonRelation,ArtistPerson.ArtistPersonID;NoDup'
  ArtistType: 'ArtistPersonType,ArtistPerson.TypeID'
  Country: 'Country,ArtistPerson.CountryID'
  Custom03: 'ArtistPersonCustom03,Custom03ID'
  Custom04: 'ArtistPersonCustom04,Custom04ID'
  FileLinks: ArtistPersonFileLinks
  RelatedTo: 'ArtistPerson,ArtistRelation.RelatedTo'
  WebLinks: ArtistPersonWebLinks;ShowAll
  WebLinkType: 'WebLinkType,WebLinks.TypeID'
mainLineTables:
  tables: 'ArtistImage,RelatedTo'
hideColumns:
  columns: 'Custom03ID,Custom04ID,MarkedQS'
userfields:
  AltName: Alt
  ArtistID: ArtistPersonID
  BirthName: Birth
  Image[1]: 'ArtistImage.Image,Image;Index=1'
  Image[2]: 'ArtistImage.Image,Image;Index=2'
  Image[3]: 'ArtistImage.Image,Image;Index=3'
  Image[4]: 'ArtistImage.Image,Image;Index=4'
  Image[5]: 'ArtistImage.Image,Image;Index=5'
  Image[6]: 'ArtistImage.Image,Image;Index=6'
  Image[7]: 'ArtistImage.Image,Image;Index=7'
  Image[8]: 'ArtistImage.Image,Image;Index=8'
  Image[9]: 'ArtistImage.Image,Image;Index=9'
  Start: 'Date1,date'
  Ended: 'Date2,date'
  RelatedTo: RelatedTo.Artist
  RelatedToSort: RelatedTo.Artists
  Thumbnail[1]: 'ArtistImage.ImageThumbnail,X;Index=1'
  Thumbnail[2]: 'ArtistImage.ImageThumbnail,X;Index=2'
  Thumbnail[3]: 'ArtistImage.ImageThumbnail,X;Index=3'
  Thumbnail[4]: 'ArtistImage.ImageThumbnail,X;Index=4'
  Thumbnail[5]: 'ArtistImage.ImageThumbnail,X;Index=5'
  Thumbnail[6]: 'ArtistImage.ImageThumbnail,X;Index=6'
  Thumbnail[7]: 'ArtistImage.ImageThumbnail,X;Index=7'
  Thumbnail[8]: 'ArtistImage.ImageThumbnail,X;Index=8'
  Thumbnail[9]: 'ArtistImage.ImageThumbnail,X;Index=9'
userfields8:
  IsArtist: Artist
  RelatedToSort: RelatedTo.ArtistPersonSort
