# CATVids - WantList
---
table:
  Name: WantList
tables:
  Format: Format
  OrderedFrom: 'AcquiredFrom,OrderedFromID,AcquiredFromID;ShowAll'
  VideoSeries: 'VideoSeries,VideoSeriesID;ShowAll'
hideColumns:
  columns: 'AcquiredFromID,MarkedQS'
userfields:
  OrderDate: 'OrderDate,date'
  OrderedFrom: OrderedFrom.AcquiredFrom
  ReleaseDate: 'ReleaseDate,date'
  Sort: OrderedFrom.AcquiredFromSort
  TitleSort: WantListSort
