# CATVids - Contents
---
table:
  Name: Contents
personColumns:
  Person: 'Name,SortBy'
tables:
  Audio: 'Audio,AudioLink.AudioID'
  AudioLink: AudioLink
  Award: 'Award,AwardLink.AwardID'
  AwardLink: AwardLink
  Color: Color
  CreditsLink: 'CreditsLink,ContentsID'
  Country: Country
  DialogLanguageLink: 'DialogLanguageLink,ContentsID'
  DialogLanguage: 'Language,DialogLanguageLink.LanguageID'
  FileLinks: FileLinks
  Keyword: 'Keyword,KeywordLink.KeywordID'
  KeywordLink: KeywordLink
  Person: 'Person,CreditsLink.PersonID'
  PersonalRating: PersonalRating
  RecordingSpeed: RecordingSpeed
  Series: Series
  Source: Source
  SubCategory: SubCategory
  SubtitleLanguageLink: 'SubtitleLanguageLink,ContentsID'
  SubtitleLanguage: 'Language,SubtitleLanguageLink.LanguageID'
  Type: 'ContentsType,TypeID'
  Video: 'Video,VideoID'
  AcquiredFrom: 'AcquiredFrom,Video.AcquiredFromID'
  Borrower: 'Borrower,Video.BorrowerID'
  Format: 'Format,Video.FormatID'
  Location: 'Location,Video.LocationID'
  VideoCustom: 'VideoCustom,Video.VideoID'
  VideoSeries: 'VideoSeries,Video.VideoSeriesID'
tables5:
  Custom04: 'ContentsCustom04,Custom04ID'
  Custom05: 'ContentsCustom05,Custom05ID'
  Custom06: 'ContentsCustom06,Custom06ID'
tables6:
  ContentsCustom: ContentsCustom
  Custom04: 'ContentsCustom04,ContentsCustom.Custom04ID'
  Custom05: 'ContentsCustom05,ContentsCustom.Custom05ID'
  Custom06: 'ContentsCustom06,ContentsCustom.Custom06ID'
  Custom20: 'ContentsCustom20,ContentsCustom.Custom20ID'
  Custom21: 'ContentsCustom21,ContentsCustom.Custom21ID'
tables7:
  AspectRatioLink: AspectRatioLink
  AspectRatio: 'AspectRation,AspectRatioLink.AspectRatioID'
  ViewHistory: ViewHistory
tables8:
  AspectRatio: AspectRatio
  AudioLanguage: 'Language,AudioLink.LanguageID'
  CertificationLink: 'CertificationLink,ContentsID'
  Certification: 'Certification,CertificationLink.CertificationID'
  Genre: 'Genre,GenreLink.GenreID'
  GenreLink: GenreLink
tables9:
  AudioFileLink: AudioFileLink
  Custom24: 'ContentsCustom24,ContentsCustom.Custom24ID'
  PrimaryGenre: 'Genre,PrimaryGenreID'
mainLineTables:
  tables: ContentsCustom
hideColumns:
  columns: MarkedQS
userfields:
  Category: Dummy
  CollectionType: Dummy
  TVCreator: Dummy
  DateAcquired: 'Video.DateAcquired,date'
  DateBorrowed: 'Video.DateBorrowed,date'
  DateDue: 'Video.DateDue,Date'
  EmailOverDueDate: 'Video.EmailOverDueDate,Date'
  EmailReminderDate: 'Video.EmailReminderDate,Date'
  EmailReservedDate: 'Video.EmailReservedDate,Date'
  Episodes: 'Dummy,Memo'
  FreeTimeEP: 'Video.FreeTimeEP,time'
  FreeTimeLP: 'Video.FreeTimeLP,time'
  FreeTimeSLP: 'Video.FreeTimeSLP,time'
  FreeTimeSP: 'Video.FreeTimeSP,time'
  LastModified: 'Video.LastModified,date'
  Registered: 'Video.Registered,Date'
  ReservedDate: 'Video.ReservedDate,Date'
  DateRecorded: 'DateRecorded,date'
  DialogLanguage: DialogLanguage.Language
  Director: Dummy
  Keyword: 'Keyword.Keyword,Memo'
  LastViewed: 'LastViewed,date'
  Length: 'Length,time'
  Person.Person: 'Person,Memo'
  SubtitleLanguage: SubtitleLanguage.Language
  Type: Type.ContentsType
  WatchingStatus: Dummy
userfields5:
  Custom07: 'Custom07,Date'
  TitleSort: ContentsSort
userfields6:
  Custom07: 'ContentsCustom.Custom07,Date'
userfields7:
  LastModified: 'LastModified,date'
  ViewHistory: 'ViewHistory.Date,Date'
userfields8:
  LastModified: 'LastModified,S'
  OrigAirDate: 'OrigAirDate,date'
userfields9:
  Custom25: 'ContentsCustom.Custom25,Date'
  Custom26: 'ContentsCustom.Custom26,Date'
  TitleSort: TitleSort
