# MusicBuddy
---
Buddy fields:
- Title: Title
- Artist: Artist
- Artist (Last, First): ArtistSort
- Series: Unknown
- Volume: Unknown
- Online Videos: Unknown
- Labels: Labels
- Catalog Number: CatalogNumber
- Country: Country
- Release Year: ReleaseYear
- Original Release Year: Unknown
- Tracks: TrackList
- Versions: Unknown
- Genres: PrimaryGenre.MainGenre
- Styles: Genre
- Composers: Unknown
- Orchestras: Unknown
- Conductors: Unknown
- Performers: Unknown
- Writers: Unknown
- Production Companies: Company
- Producers: Unknown
- Description: Unknown
- Edition: Unknown
- Media: Format
- Format: Unknown
- Content Type: FormatGroup
- Length: PlayingTime
- Vinyl Size: Unknown
- Vinyl Speed: Unknown
- List Price: Value
- Language: Unknown
- Packaging: Packaging
- Number Of Volumes: DiscCount
- UPC-EAN13: BarCode
- Favorites: Unknown
- Rating: PersonalRating
- Physical Location: Location
- Loaned To: Borrower
- Date Loaned: DateBorrowed
- Borrowed From: Unknown
- Date Borrowed: Unknown
- Returned from Borrow: Unknown
- Not Owned Reason: Unknown
- Quantity: Unknown
- Cover Condition: ConditionSleeveSort
- Condition: ConditionRecordSort
- Recommended By: Unknown
- Date Added: Registered
- User Supplied ID: Unknown
- User Supplied Descriptor: Unknown
- Tags: Unknown
- Purchase Date: DateAcquired
- Purchase Place: AcquiredFrom  
- Purchase Price: Price
- Notes: Notes
- discogs Release ID: Unknown
- Category: Category
- Wish List: Unknown
- Previously Owned: Unknown
- Uploaded Image URL: Unknown
- Activities: Unknown