# Internet sites list
---
Internet sites:
- name: Fans of FNProgramvare
  website:
  - Facebook: https://www.facebook.com/groups/FNPrgFans
  - Forum: https://fansoffnprg.proboards.com
- name: Other
  website:
  - BookBuddy, MovieBuddy & MusicBuddy: https://www.kimicoapps.com/
  - HanDBase: https://www.reddit.com/r/handbase/
  - List: http://www.lowtek.ca/list
 