# Internet sites list
---
Internet sites:
- name: Fans of FNProgramvare
  website:
  - Facebook: https://www.facebook.com/groups/FNPrgFans
  - Forum: https://fansoffnprg.proboards.com
- name: Other
  website:
  - HanDBase: https://www.reddit.com/r/handbase/
  - iCalender: https://icalendar.org/
  - List: http://www.lowtek.ca/list
  - MariaDB: https://mariadb.com
  - MySQL: https://www.mysql.com
  - Paradox: http://www.dosdays.co.uk/topics/Software/borland_paradox.php
  - PostgreSQL: https://www.postgresql.org
  - Pilot-DB: http://pilot-db.sourceforge.net
  - SQL Server: https://docs.microsoft.com/en-us/sql/sql-server/
